---
title: "假释小国寡民"
author: "倏忽辟窍"
date: 2025.11.17
---

假释盖有两种方式，一是凭借原意，放大范围，尽量获取它的奥义以得到新的假释，二是只看效果，缩小范围，或取交集，抓住实在，再做描绘。

此篇是只看效果，缩小范围。

排除掉其他干扰因素，小国寡民的物理表现是，沟通上较为容易，距离上预期有效。以村落为例，距离上大约可以以步行在十五分钟内从村头到村尾。沟通受限于距离，也算是方便。

我们再看小国寡民的内涵上，从诸子百家的目标效果看，先秦诸子是文脉相承的。

请看百家各自的法术闪亮登场。

儒家依赖士君子，依赖个人，先秦之前，儒家的指导思想是修习儒术，修养自己，进而做官礼束诸侯，以治理之功获取封地，庇护百姓；或做相邦，为天下看匣子守宝箱。但是战国之后，获取封地的几率极低，这条基本宣告孔子为代表的儒家的失败，匣子宝箱看守失败代表着孔子弟子的代表诸如冉有和季路，也失败了。

墨家认识到了这一点，只相邦还不够，只思想的力量干预还不够，也要有物理的干预力量。于是墨家叛儒，墨家依赖墨者集体，依赖组织，引导非攻和交相利，使诸侯明白退一步尚有利可图，进一步则得不偿失。但墨家的声音更多体现的是反对战争上，墨家的非攻和交相利是以国为单位的，以国为体现的，墨家虽然保护弱国，却对弱国的百姓无可奈何，表现上和儒家好不了多少，他们走了，百姓还是原来的样子。人民的本性是消极躺平的，所谓古之学者为己。标榜兼爱，大家却依然不能躺平，你没来我这样，你来了我还这样，你不是白来了吗？

非攻并没有夯实国人和野人的根基，依然是儒家的路子，只是多了一个诸侯国交相利的概念。

墨家的非攻到底有些狭隘了。非攻应该有更适应的更广阔的地方，不可因为一时的高光而一直让它独享。

墨家还是做官那套，对人民，对百姓，却是于事无补。墨家就像大河中的沙洲一样，有墨翟在，林木茂盛，花草媲美，一时风光无两，后面没有墨子这棵大树锁定，便果然被冲的不见踪影。墨家虽然有些好处，却不是中流砥石。当然，这是时代的限制，小国寡民的要素尚到不了依托人民依托百姓的地步。

儒家荀子也认识到了这一点，于是背儒生法，既然大势果然是要天下一统的，果然是要君主集权的，那便制天应命，头发丝系老虎，以理服人，也可使君舟民水，君舟民沙。像大河一样，当民水构成之时，冲击所得的民沙也就随之构成了，当舟太大，水太浅，岂不就是瓮中之鳖么。总之儒生法家，使商周六百年八百年，被腰斩降为三百年四百年，天下的形势就和黄河一样，如地上悬河。君主的位格表面上是被提拔到无限高，实际上是被腰斩分割了。后面有贪官污吏，继续败坏，语境里暂且忽视其代价的话，他们又败三百年四百年到两百年以下，忽略代价的话，谁说腐儒犬儒就不干事呢。

老君描述了社会的理想状态应该是什么样的，也就是小国寡民。面对小国寡民的底限要求，百家必然不肯也不能真的作用于底线。诸侯就像鱼一样，百家的法术即是渔网，既要让鱼落网，又不能真的收网，更不能让鱼逃跑，最好是鱼儿也不能察觉，还要给鱼好处。如果只作用于底限，对鱼儿没有助益，那诸侯凭什么宽容他们呢。

经过千年的循环，千年的沉淀，小说家许仲琳，写《封神演义》的那一位，他做了理论的进一步探索总结说明，演义中有个相，代表青年力量的截教多妖魔鬼怪，被代表中老年力量的阐教联合外教毒打破教。

人群的主体是下愚群体，发动下愚群体，必然是妖魔鬼怪居多，这大概是诸子不做教主的原因。就像是水映照自然一样，自然是什么样子，水就照映成什么样子，诸子究竟不是圣人，或许能改天换地，却不能袖里乾坤。

如封神所说，静颂黄庭三两卷，东投西土有缘人，若不自正反而事多，没什么好怪的。天尊的徒弟不也有投西土的么，百家的弟子也一样，孔子弟子冉有季路就是这样的啊。

但世界人民对美好生活的向往是一致的。不同于小说家对集体审问的点到即止，世界人民顺应潮流送来了社会主义，尝试以阶级集体为单位的小国寡民联结。我们的历史，我们的文脉，从依赖共主圣王，到依赖士君子的个人，到依赖组织集体，到依赖君主，最后终于回过头来依赖自己，却是一个人也跑不掉。

尤其是随着电气时代的到来，小国寡民的范围切实地彻底地发生了变化。互联网使沟通接近即时，内燃机，我指主要是摩托车加上自行车的补充使小国寡民的范围扩大到了一个乡镇。

这里大概明确了古今小国寡民的物理不同后，再来看小国寡民的实在。

小国寡民的民在甲骨文里的意思是刺瞎眼睛的奴隶^min。在君愚君，在民愚民。寡民是少民，少用民，君子是民，墨者是民，组织是民，君主也是民。小国百姓的表现为不用机巧，不用管理，表述为纯朴自然，亲力亲为，百姓自然承担民的任务。在今天的世界，阶级站出来后，人民的经验集合后，或者可以表述为一，理想情况下既没有人，也没有民，没有人和民的分别，没有人和人、人和民、民和民的冲突，人就是民，民就是人，人民居然一体，也必然一体，果然所有人都是民了，那就没有民了，如此便可民最寡。　

所传科学无国界，资本无国界，有些群体在小国寡民上精明到了没有地域，没有国别的限制。真是令落后的人气闷啊。比起他们，我们的差距还差一个任意门的科技呢。但好歹有天时不如地利，地利不如人和以聊作安慰。

网友常说宏大叙事，实际上通过宏大叙事达到世界范围就会发现，墨家是世界的，欧美主导全球化交相利，儒家反而是国别的，贸易保护、文化保护和军事保护。

再进一步，从人类视角端详，世界人民对美好生活的向往是一致的，这是百家文脉一脉相承的根由所在。

阶级斗争是小国寡民的最终之术，是小国寡民的奥义所在，再不可能有长进了，如果摩托车加互联网不可行，那任意门加互联网也不会可行。我们的最终结果是或者小国寡民或者赛博朋克。

只看效果，缩小范围，再取交集，我们从百家在小国寡民的实践中可以提炼出一点，关键在于非攻的把握，或者更明确地说是对非攻的体验，对意识的反制，对躺平的妥协。

要跟进践行小国寡民，必要先白话文运动，在集体层面抹掉信息差以构成基本默契。要跟进践行阶级斗争，必然是选取数镇之地，抄世界人民的作业，解放生产力，然后继续抄作业继续选取地域，重复作业。除现有资本外，也夯实集体资本，主要是阶级资本。

有次我反驳别人赞同的性恶论，他说反对孟子，反对孟子没问题，对性善论性恶论模糊就不行好了。

人性是出于人群在映照环境后的集体表现就趋于那样，于是被后生二次映照。人道取代天道，但调解不如天道，天道飘风不终朝，骤雨不终日，随着人道依赖的个体仁人义士的惨死，人道必然表现有滞后性与崩坏特性。这是本恶所在。

孟子说人性本善是因为他们还活着。荀子说人性本恶是因为他们活着的意义也不大。如善良篇说的那样，闻一知五以上的人五千年就那几个，相对现实的是文斗构成一定的均势。

网上问问题的很多，调侃人的也不少，有烦恼教育的，有青少年不祥的，有青年不祥的，有中年不祥的，老年不祥的也有。白话文运动，也应该继续运动一波，构成互联网上的上山下乡气象，人皆各复归其命。

朱熹说如葆赤子，心诚而求之，即使差一点，也不会离很多。与其增添各种专家，各种家长，各种医生，各种大师，不如增添几篇白话文更简单些。果真形成文化上上山下乡气象，人也大概能有几分幼而徇齐，长而敦敏的气象。

天下自战国后仍是战国，或许是一个人都跑不掉，或许是一个人都跑不掉。

此为小国寡民秘义。

解天人之分如精卫填海，我今亦填之。
